declare const THREE: any;

import { generateAllTextures } from './pbrGenerator/generator';
import type { GeneratorParams } from './pbrGenerator/types';

// ─── User-specified PBR generator params ───
const WALL_PBR_PARAMS: GeneratorParams = {
  rows: 7,
  cols: 30,
  heightVar: 0,
  roughness: 45,
  gap: 8,
  mortarColor: '#b09870',
  bevel: 90,
  texture: 70,
  cracks: 70,
  normalStr: 3.4,
};

const VARIANT_COUNT = 4;
const TILE_SIZE = 512;
const ATLAS_SIZE = TILE_SIZE * 2; // 1024 — 2×2 atlas

function makeCanvas(w: number, h: number): HTMLCanvasElement {
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return c;
}

export interface PBRTextureSet {
  diffuse: any;   // THREE.CanvasTexture
  normal: any;
  height: any;
  roughness: any;
}

/**
 * Generate a 2×2 atlas (1024×1024) of 4 PBR texture variants.
 * Each variant is a 512×512 tile generated by the stone wall PBR generator.
 * Returns Four THREE.CanvasTexture objects: diffuse, normal, height, roughness.
 */
export function createPBRWallTextures(): PBRTextureSet {
  // Atlas canvases (1024×1024)
  const atlasDiffuse = makeCanvas(ATLAS_SIZE, ATLAS_SIZE);
  const atlasNormal = makeCanvas(ATLAS_SIZE, ATLAS_SIZE);
  const atlasHeight = makeCanvas(ATLAS_SIZE, ATLAS_SIZE);
  const atlasRoughness = makeCanvas(ATLAS_SIZE, ATLAS_SIZE);

  const ctxD = atlasDiffuse.getContext('2d')!;
  const ctxN = atlasNormal.getContext('2d')!;
  const ctxH = atlasHeight.getContext('2d')!;
  const ctxR = atlasRoughness.getContext('2d')!;

  // Fill normal atlas with default flat normal (128,128,255)
  ctxN.fillStyle = 'rgb(128,128,255)';
  ctxN.fillRect(0, 0, ATLAS_SIZE, ATLAS_SIZE);

  // Generate 4 variants and composite into atlas
  for (let v = 0; v < VARIANT_COUNT; v++) {
    const tileD = makeCanvas(TILE_SIZE, TILE_SIZE);
    const tileN = makeCanvas(TILE_SIZE, TILE_SIZE);
    const tileH = makeCanvas(TILE_SIZE, TILE_SIZE);
    const tileR = makeCanvas(TILE_SIZE, TILE_SIZE);

    generateAllTextures(WALL_PBR_PARAMS, {
      diffuse: tileD,
      normal: tileN,
      height: tileH,
      roughness: tileR,
    });

    // Atlas layout: variant 0=TL, 1=TR, 2=BL, 3=BR
    const ox = (v % 2) * TILE_SIZE;
    const oy = Math.floor(v / 2) * TILE_SIZE;

    ctxD.drawImage(tileD, ox, oy);
    ctxN.drawImage(tileN, ox, oy);
    ctxH.drawImage(tileH, ox, oy);
    ctxR.drawImage(tileR, ox, oy);
  }

  const diffuseTex = new THREE.CanvasTexture(atlasDiffuse);
  diffuseTex.colorSpace = THREE.SRGBColorSpace;

  const normalTex = new THREE.CanvasTexture(atlasNormal);
  normalTex.colorSpace = THREE.NoColorSpace;

  const heightTex = new THREE.CanvasTexture(atlasHeight);
  heightTex.colorSpace = THREE.NoColorSpace;

  const roughnessTex = new THREE.CanvasTexture(atlasRoughness);
  roughnessTex.colorSpace = THREE.NoColorSpace;

  // All atlas textures: clamp to edge (no repeat — we handle variant UVs manually)
  for (const tex of [diffuseTex, normalTex, heightTex, roughnessTex]) {
    tex.wrapS = THREE.ClampToEdgeWrapping;
    tex.wrapT = THREE.ClampToEdgeWrapping;
    tex.minFilter = THREE.LinearMipMapLinearFilter;
    tex.magFilter = THREE.LinearFilter;
    tex.generateMipmaps = true;
  }

  return { diffuse: diffuseTex, normal: normalTex, height: heightTex, roughness: roughnessTex };
}

// ─── Floor texture (unchanged) ───

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number, r: number
): void {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
  ctx.fill();
}

export function createFloorTexture(): any {
  const size = 256;
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;

  ctx.fillStyle = '#5a5348';
  ctx.fillRect(0, 0, size, size);

  const cols = 4;
  const rowCount = 4;
  const cellW = size / cols;
  const cellH = size / rowCount;

  for (let r = 0; r < rowCount; r++) {
    for (let c = 0; c < cols; c++) {
      const bx = c * cellW + cellW * 0.07 + Math.random() * cellW * 0.06;
      const by = r * cellH + cellH * 0.07 + Math.random() * cellH * 0.06;
      const bw = cellW * 0.78 + Math.random() * cellW * 0.08;
      const bh = cellH * 0.78 + Math.random() * cellH * 0.08;
      const lightness = 52 + Math.random() * 22;
      const hue = 28 + Math.random() * 12;

      ctx.fillStyle = `hsl(${hue}, 12%, ${lightness}%)`;
      roundRect(ctx, bx, by, bw, bh, 3);

      for (let i = 0; i < 10; i++) {
        const nx = bx + Math.random() * bw;
        const ny = by + Math.random() * bh;
        const nl = lightness + (Math.random() - 0.5) * 10;
        ctx.fillStyle = `hsla(${hue}, 10%, ${nl}%, 0.25)`;
        ctx.fillRect(nx, ny, 2 + Math.random() * 4, 2 + Math.random() * 3);
      }

      if (Math.random() < 0.25) {
        ctx.fillStyle = `hsla(100, 40%, ${25 + Math.random() * 12}%, 0.45)`;
        for (let i = 0; i < 4; i++) {
          ctx.beginPath();
          ctx.arc(bx + Math.random() * 8, by + Math.random() * 8, 1 + Math.random() * 2, 0, Math.PI * 2);
          ctx.fill();
        }
      }
    }
  }

  const texture = new THREE.CanvasTexture(canvas);
  texture.wrapS = THREE.RepeatWrapping;
  texture.wrapT = THREE.RepeatWrapping;
  return texture;
}

export function createBallTexture(): any {
  const size = 128;
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;

  ctx.fillStyle = '#7a7268';
  ctx.fillRect(0, 0, size, size);

  for (let i = 0; i < 350; i++) {
    const x = Math.random() * size;
    const y = Math.random() * size;
    const l = 38 + Math.random() * 30;
    ctx.fillStyle = `hsl(25, 8%, ${l}%)`;
    ctx.fillRect(x, y, 2 + Math.random() * 3, 2 + Math.random() * 3);
  }

  return new THREE.CanvasTexture(canvas);
}
